version: '3.8'

services:

  orders:
    build:
      context: .
      dockerfile: ./apps/orders/dockerfile
      target: development
    command: npm run start:dev orders
    env_file:
      - ./apps/orders/.env
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
    depends_on:
      - billing
      - auth
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'

  billing:
    build:
      context: .
      dockerfile: ./apps/billing/dockerfile
      target: development
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
    command: npm run start:dev billing
    env_file:
      - ./apps/billing/.env
    depends_on:
      - rabbitmq
      - auth
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  products:
    build:
      context: .
      dockerfile: ./apps/products/dockerfile
      target: development
    command: npm run start:dev products
    links:
      - redis
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3003:3003'
  users:
    build:
      context: .
      dockerfile: ./apps/users/dockerfile
      target: development
    command: npm run start:dev users
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3004:3004'
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/dockerfile
      target: development
    command: npm run start:dev auth
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3005:3005'


  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    depends_on:
      - postgres
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin12
    ports: 
      - "8080:80"


